### ISSUE TITLE
Changes to Whitelist username creation

### ISSUE THREAD

**Issue by SteveyO** [cDima/Hue#1]
Hi Dmitry,

I work for Philips Hue Developer Support (we have had contact before).  In case you were not aware, in a few months time we will be changing the way usernames are created on the bridge (for security reasons).  Custom whitelist usernames will no longer be allowed and the bridge randomly 
generated username must be used instead.  Please see below link for more information:
http://www.developers.meethue.com/documentation/important-whitelist-changes

In HueBridge.cs (line 91) I see you are passing in the username in your POST body. This will start failing around February 2016,  so it will need removing/changing.   The randomly generated bridge username will be returned in the bridge response and this must be used instead.  Apologies for the inconvenience.

Thanks
Steve

**Comment by cDima** [comment]
Thank you Steve for reaching out. I am aware of the changes to the bridge, I will make appropriate changes. Thanks!

**Comment by SteveyO** [comment]
Great! Thanks for the fast response.  I would appreciate it if you could let me know when done.  Replying to the issue should be fine.  :-)

**Comment by cDima** [comment]
Hih Steve, this is done.

On a related note, how do applications get selected for the top of
"Selected apps" for Hue on iOS and Android? I would love for ambieye.com to
be featured (iOS and Android):

http://www.developers.meethue.com/otherapps/otherAppsIOS.html
http://www.developers.meethue.com/otherapps/otherAppsAndroid.html

Thanks.

On Tue, Nov 3, 2015 at 8:04 AM, Steve notifications@github.com wrote:

> Great! Thanks for the fast response. I would appreciate it if you could
> let me know when done. Replying to the issue should be fine. :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cDima/Hue/issues/1#issuecomment-153346551.

## 

*Dmitry Sadakov *
Consultant – Web Technology  | Gemini Systems | A&M | 600 Madison Ave| New
York, NY | Mobile +16468531955
sadakov.com | linkedin http://linkedin.com/in/sadakov | stackoverflow
http://stackoverflow.com/users/82054/cdima | github
https://github.com/cDima | g+ http://www.google.com/profiles/sadakov |
facebook https://www.facebook.com/sadakov | vk http://vk.com/sadakov |
skype:dmitry.sadakov

**Comment by SteveyO** [comment]
Hi Dmitry,   Fantastic!  Thanks for your fast response and action on this.  I will send you an email regarding your question
Steve
